<?php
$a = ["512"=>["site"=>"https://startupbase.com.br/c/startups/be220-conteudo-digital", "emailDaStartup"=>"mailto:contato@be220.com", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Be220 Conteúdo Digital", "siteDaStartup"=>"www.be220.com/"], "513"=>["site"=>"https://startupbase.com.br/c/startups/be-on-seguranca-colaborativa", "emailDaStartup"=>"mailto:gustavo@squadraconsultoria.com.br", "ano"=>"2018", "municipio"=>"Porto Alegre - RS", "nome"=>"Be On - Segurança Colaborativa", "siteDaStartup"=>"appbeon.com"], "514"=>["site"=>"https://startupbase.com.br/c/startups/baz-negocios-de-a-a-z", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"BAZ Negócios de A a Z", "siteDaStartup"=>"baz.com.br/"], "515"=>["site"=>"https://startupbase.com.br/c/startups/bandolim-maestro", "emailDaStartup"=>"mailto:contato@bandolim.ba", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"Bandolim - Maestro", "siteDaStartup"=>"www.bandolim.ba/"], "516"=>["site"=>"https://startupbase.com.br/c/startups/bambu-alimentos", "emailDaStartup"=>"mailto:contato@bambualimentos.com", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"Bambu Alimentos", "siteDaStartup"=>"bambualimentos.com/"], "517"=>["site"=>"https://startupbase.com.br/c/startups/balladapp", "emailDaStartup"=>"mailto:contato@baladapp.com.br", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"BalladApp", "siteDaStartup"=>"baladapp.com.br/"], "518"=>["site"=>"https://startupbase.com.br/c/startups/bae-digital-ltda", "ano"=>"2021", "municipio"=>"Campo Bom - RS", "nome"=>"Bae Digital Ltda", "siteDaStartup"=>""], "519"=>["site"=>"https://startupbase.com.br/c/startups/baby-gym-academia-para-bebes", "emailDaStartup"=>"mailto:contato@meubabygym.com", "ano"=>"2013", "municipio"=>"Porto Alegre - RS", "nome"=>"Baby Gym - Academia para bebês", "siteDaStartup"=>""], "520"=>["site"=>"https://startupbase.com.br/c/startups/baby-checkin", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"Baby Check-in"], "521"=>["site"=>"https://startupbase.com.br/c/startups/aztec-online-solutions", "emailDaStartup"=>"mailto:contato@aztecweb.net", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Aztec Online Solutions", "siteDaStartup"=>"aztecweb.net/"], "522"=>["site"=>"https://startupbase.com.br/c/startups/axbadministradoradecartoesdecredito", "emailDaStartup"=>"mailto:giovanimachado@axb.digital", "ano"=>"2021", "municipio"=>"Porto Alegre - RS", "nome"=>"AXBAdministradoradeCartõesdeCrédito", "siteDaStartup"=>""], "523"=>["site"=>"https://startupbase.com.br/c/startups/avela-big-data", "emailDaStartup"=>"mailto:andrea@avelapublicaffairs.com", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Avelã Big Data", "siteDaStartup"=>"www.observatorio.com.br"], "524"=>["site"=>"https://startupbase.com.br/c/startups/avctoris", "emailDaStartup"=>"mailto:rrm32@e-marcas.com.br", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"Avctoris", "siteDaStartup"=>"www.avctoris.com"], "525"=>["site"=>"https://startupbase.com.br/c/startups/avant-solar", "emailDaStartup"=>"mailto:contato@avantsolar.com.br", "ano"=>"2017", "municipio"=>"Porto Alegre - RS", "nome"=>"Avant Solar", "siteDaStartup"=>"avantsolar.com.br/"], "526"=>["site"=>"https://startupbase.com.br/c/startups/avacon-technology", "emailDaStartup"=>"mailto:CONTATO@AVACONSA.COM.BR", "ano"=>"2016", "municipio"=>"Canoas - RS", "nome"=>"Avacon Technology", "siteDaStartup"=>"www.avaconsa.com.br/"], "527"=>["site"=>"https://startupbase.com.br/c/startups/autoridade-fitness", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"Autoridade Fitness", "siteDaStartup"=>"espaco.autoridadefitness.com/"], "528"=>["site"=>"https://startupbase.com.br/c/startups/auster-tecnologia", "emailDaStartup"=>"mailto:contato@austertec.com", "ano"=>"2016", "municipio"=>"Santa Maria - RS", "nome"=>"Auster Tecnologia", "siteDaStartup"=>""], "529"=>["site"=>"https://startupbase.com.br/c/startups/aurea", "ano"=>"2013", "municipio"=>"Porto Alegre - RS", "nome"=>"AUREA", "siteDaStartup"=>"useaurea.com/"], "530"=>["site"=>"https://startupbase.com.br/c/startups/atraia", "emailDaStartup"=>"mailto:contato@atraia.com", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"Atraia", "siteDaStartup"=>"www.atraia.com/quem-somos"], "531"=>["site"=>"https://startupbase.com.br/c/startups/atendare", "emailDaStartup"=>"mailto:katiuscia@atendare.com", "ano"=>"2018", "municipio"=>"Três de Maio - RS", "nome"=>"Atendare", "siteDaStartup"=>"atendare.com"], "532"=>["site"=>"https://startupbase.com.br/c/startups/arpac", "emailDaStartup"=>"mailto:eduardo@arpacbrasil.com.br", "ano"=>"2012", "municipio"=>"São Leopoldo - RS", "nome"=>"Arpac", "siteDaStartup"=>"arpacbrasil.com.br"], "533"=>["site"=>"https://startupbase.com.br/c/startups/aprocci", "emailDaStartup"=>"mailto:claudia.approcci@gmail.com", "ano"=>"2012", "municipio"=>"Porto Alegre - RS", "nome"=>"Aprocci", "siteDaStartup"=>"claudiaentre.wixsite.com/approcci2"], "534"=>["site"=>"https://startupbase.com.br/c/startups/aposentado-em-acao", "emailDaStartup"=>"mailto:contato@aposentadoemacao.com.br", "ano"=>"2017", "municipio"=>"Porto Alegre - RS", "nome"=>"Aposentado Em Ação", "siteDaStartup"=>"www.aposentadoemacao.com.br/"], "535"=>["site"=>"https://startupbase.com.br/c/startups/apoiase", "emailDaStartup"=>"mailto:contato@apoia.se", "ano"=>"2013", "municipio"=>"Porto Alegre - RS", "nome"=>"Apoia.se", "siteDaStartup"=>"apoia.se"], "536"=>["site"=>"https://startupbase.com.br/c/startups/apecatus", "emailDaStartup"=>"mailto:anette.pegas@APECATUS.COM", "ano"=>"2019", "municipio"=>"Santa Cruz do Sul - RS", "nome"=>"APECATUS", "siteDaStartup"=>"www.apecatus.com"], "537"=>["site"=>"https://startupbase.com.br/c/startups/any3", "emailDaStartup"=>"mailto:contato@any3.com.br", "ano"=>"2014", "municipio"=>"Santa Maria - RS", "nome"=>"Any3", "siteDaStartup"=>"www.any3.com.br/"], "538"=>["site"=>"https://startupbase.com.br/c/startups/anota-ai", "emailDaStartup"=>"mailto:contato@anota.ai", "ano"=>"2017", "municipio"=>"Rio Grande - RS", "nome"=>"Anota AI", "siteDaStartup"=>"www.anota.ai"], "539"=>["site"=>"https://startupbase.com.br/c/startups/anima-pocket", "emailDaStartup"=>"mailto:adriana@animapocket.com.br", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"Anima Pocket", "siteDaStartup"=>"www.animapocket.com.br/"], "540"=>["site"=>"https://startupbase.com.br/c/startups/analitus", "emailDaStartup"=>"mailto:sac@analitus.com", "ano"=>"2012", "municipio"=>"Caxias do Sul - RS", "nome"=>"Analitus", "siteDaStartup"=>"analitus.com.br/"], "541"=>["site"=>"https://startupbase.com.br/c/startups/amipet", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"amipet", "siteDaStartup"=>"www.amipet.com.br/"], "542"=>["site"=>"https://startupbase.com.br/c/startups/alugadireto", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Alugadireto", "siteDaStartup"=>"www.alugadiretors.com.br/"], "543"=>["site"=>"https://startupbase.com.br/c/startups/aluga-mais-app-ltda", "emailDaStartup"=>"mailto:alugamais@alugamaisapp.com.br", "ano"=>"2021", "municipio"=>"Passo Fundo - RS", "nome"=>"Aluga Mais App Ltda", "siteDaStartup"=>""], "544"=>["site"=>"https://startupbase.com.br/c/startups/alu", "emailDaStartup"=>"mailto:contato@meualu.com", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Alu", "siteDaStartup"=>"www.meualu.com/"], "545"=>["site"=>"https://startupbase.com.br/c/startups/altervision", "emailDaStartup"=>"mailto:contato@altervision.com.br", "ano"=>"2020", "municipio"=>"Porto Alegre - RS", "nome"=>"AlterVision", "siteDaStartup"=>""], "546"=>["site"=>"https://startupbase.com.br/c/startups/alster", "emailDaStartup"=>"mailto:info@alster.esp.br", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Alster", "siteDaStartup"=>"alster.esp.br/"], "547"=>["site"=>"https://startupbase.com.br/c/startups/alpago", "emailDaStartup"=>"mailto:contato@alpago.com.br", "ano"=>"2015", "municipio"=>"Pelotas - RS", "nome"=>"Alpago", "siteDaStartup"=>"www.alpago.com.br/"], "548"=>["site"=>"https://startupbase.com.br/c/startups/alloy", "emailDaStartup"=>"mailto:parceiro@alloy.al", "ano"=>"2019", "municipio"=>"Santa Maria - RS", "nome"=>"Alloy", "siteDaStartup"=>"www.alloy.al/"], "549"=>["site"=>"https://startupbase.com.br/c/startups/allexo-tecnologia", "emailDaStartup"=>"mailto:comercial@allexo.com.br", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"Allexo Tecnologia", "siteDaStartup"=>"allexo.com.br/"], "550"=>["site"=>"https://startupbase.com.br/c/startups/ai-acheimoveisonline", "ano"=>"2020", "municipio"=>"Porto Alegre - RS", "nome"=>"ai - acheimoveis.online"], "551"=>["site"=>"https://startupbase.com.br/c/startups/agroeducar", "emailDaStartup"=>"mailto:telmo.lena@gmail.com", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"Agroeducar", "siteDaStartup"=>"www.linkedin.com/company/agroeducar"], "552"=>["site"=>"https://startupbase.com.br/c/startups/agricon-business", "emailDaStartup"=>"mailto:eduarda@agriconbusness.com", "ano"=>"2019", "municipio"=>"Porto Alegre - RS", "nome"=>"Agricon Business", "siteDaStartup"=>"www.agriconbusiness.com"], "553"=>["site"=>"https://startupbase.com.br/c/startups/agrare-tecnologia-e-gestao", "emailDaStartup"=>"mailto:alex@agrare.com.br", "ano"=>"2018", "municipio"=>"Passo Fundo - RS", "nome"=>"Agrare - Tecnologia e Gestão", "siteDaStartup"=>"www.agrare.com.br"], "554"=>["site"=>"https://startupbase.com.br/c/startups/agextec", "emailDaStartup"=>"mailto:cesar@agextec.com.br", "ano"=>"2017", "municipio"=>"Ijuí - RS", "nome"=>"AgexTec", "siteDaStartup"=>"www.agextec.com.br"], "555"=>["site"=>"https://startupbase.com.br/c/startups/agente-g-solucoes-empresariais", "emailDaStartup"=>"mailto:roberto@agenteg.com.br", "ano"=>"2016", "municipio"=>"Caxias do Sul - RS", "nome"=>"Agente G Soluções Empresariais", "siteDaStartup"=>"www.agenteg.com.br"], "556"=>["site"=>"https://startupbase.com.br/c/startups/agencieme", "ano"=>"2017", "municipio"=>"Viamão - RS", "nome"=>"Agencie.me", "siteDaStartup"=>"www.agencie.me"], "557"=>["site"=>"https://startupbase.com.br/c/startups/agenciattb", "emailDaStartup"=>"mailto:contato@agenticattb.com", "ano"=>"2017", "municipio"=>"Porto Alegre - RS", "nome"=>"AgenciaTTB", "siteDaStartup"=>"www.agenciattb.com/"], "558"=>["site"=>"https://startupbase.com.br/c/startups/afortunado", "emailDaStartup"=>"mailto:contato@afortunado.com.br", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"Afortunado", "siteDaStartup"=>"www.afortunado.com.br/"], "559"=>["site"=>"https://startupbase.com.br/c/startups/aeronaves-remotamente-pilotadas-de-alta-capacidade", "emailDaStartup"=>"mailto:contato@arpacbrasil.com.br", "ano"=>"2012", "municipio"=>"São Leopoldo - RS", "nome"=>"Aeronaves Remotamente Pilotadas de Alta Capacidade", "siteDaStartup"=>"www.arpacbrasil.com.br/"], "560"=>["site"=>"https://startupbase.com.br/c/startups/aero-topografia", "emailDaStartup"=>"mailto:contato@aerotopografia.com.br", "ano"=>"2018", "municipio"=>"Santa Rosa - RS", "nome"=>"AERO Topografia", "siteDaStartup"=>"www.aerotopografia.com.br"], "561"=>["site"=>"https://startupbase.com.br/c/startups/adeus-rotina", "emailDaStartup"=>"mailto:contato@adeusrotina.com.br", "ano"=>"2013", "municipio"=>"Porto Alegre - RS", "nome"=>"Adeus Rotina", "siteDaStartup"=>"www.adeusrotina.com.br"], "562"=>["site"=>"https://startupbase.com.br/c/startups/addicionei", "emailDaStartup"=>"mailto:comercial@addicionei.com.br", "ano"=>"2013", "municipio"=>"Porto Alegre - RS", "nome"=>"addicionei", "siteDaStartup"=>"addicionei.com.br/"], "563"=>["site"=>"https://startupbase.com.br/c/startups/aciz", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"ACIZ", "siteDaStartup"=>"www.aciz.com.br"], "564"=>["site"=>"https://startupbase.com.br/c/startups/acerto-facil", "emailDaStartup"=>"mailto:sac@acertofacil.com.br", "ano"=>"2017", "municipio"=>"Porto Alegre - RS", "nome"=>"Acerto Fácil", "siteDaStartup"=>"acertofacil.com.br/"], "565"=>["site"=>"https://startupbase.com.br/c/startups/acelera-mei", "emailDaStartup"=>"mailto:contato@aceleramei.com.br", "ano"=>"2014", "municipio"=>"Santa Maria - RS", "nome"=>"Acelera MEI", "siteDaStartup"=>"www.aceleramei.com.br/"], "566"=>["site"=>"https://startupbase.com.br/c/startups/abreast-prospeccao-corporativa", "emailDaStartup"=>"mailto:matheus@abreast.net.br", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"ABREAST PROSPECÇÃO CORPORATIVA", "siteDaStartup"=>"abreast.net.br/"], "567"=>["site"=>"https://startupbase.com.br/c/startups/abm-lux", "emailDaStartup"=>"mailto:contact@abmlux.com", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"ABM LUX", "siteDaStartup"=>"www.abmlux.com"], "568"=>["site"=>"https://startupbase.com.br/c/startups/aadtools", "ano"=>"2015", "municipio"=>"Canoas - RS", "nome"=>"AAdTools"], "569"=>["site"=>"https://startupbase.com.br/c/startups/a00s", "emailDaStartup"=>"mailto:suporte@a00s.com", "ano"=>"2015", "municipio"=>"Nova Prata - RS", "nome"=>"A00s", "siteDaStartup"=>"a00s.com/"], "570"=>["site"=>"https://startupbase.com.br/c/startups/4por100", "emailDaStartup"=>"mailto:contato@4por100.com.br", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"4POR100", "siteDaStartup"=>"www.4por100.com.br/"], "571"=>["site"=>"https://startupbase.com.br/c/startups/4all-tecnologia", "emailDaStartup"=>"mailto:contato@4all.com", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"4all Tecnologia", "siteDaStartup"=>"www.4all.com"], "572"=>["site"=>"https://startupbase.com.br/c/startups/400g", "emailDaStartup"=>"mailto:contato@400g.com.br", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"400g", "siteDaStartup"=>"www.facebook.com/sou400g/"], "573"=>["site"=>"https://startupbase.com.br/c/startups/3s-solar-sustainable-solutions", "emailDaStartup"=>"mailto:fernandoasantos7@gmail.com", "ano"=>"2021", "municipio"=>"Novo Hamburgo - RS", "nome"=>"3S - Solar Sustainable Solutions", "siteDaStartup"=>"www.energia3s.com.br"], "574"=>["site"=>"https://startupbase.com.br/c/startups/3layer-tecnologia", "emailDaStartup"=>"mailto:comercial@3layer.com.br", "ano"=>"2015", "municipio"=>"Porto Alegre - RS", "nome"=>"3layer Tecnologia", "siteDaStartup"=>"3layer.com.br"], "575"=>["site"=>"https://startupbase.com.br/c/startups/3dprotos", "emailDaStartup"=>"mailto:contato@3dprotos.com.br", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"3DProtos", "siteDaStartup"=>"www.3dprotos.com.br/"], "576"=>["site"=>"https://startupbase.com.br/c/startups/36z", "emailDaStartup"=>"mailto:alexandre@plataforma36z.com.br", "ano"=>"2020", "municipio"=>"Porto Alegre - RS", "nome"=>"36Z", "siteDaStartup"=>"www.plataforma36z.com.br"], "577"=>["site"=>"https://startupbase.com.br/c/startups/2bface", "emailDaStartup"=>"mailto:2bface@rua.com.br", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"2bface", "siteDaStartup"=>"2bface.com/"], "578"=>["site"=>"https://startupbase.com.br/c/startups/1bem", "emailDaStartup"=>"mailto:fazer@1bem.com.br", "ano"=>"2014", "municipio"=>"São Leopoldo - RS", "nome"=>"1Bem", "siteDaStartup"=>"www.1bem.com.br"], "579"=>["site"=>"https://startupbase.com.br/c/startups/123projetei", "emailDaStartup"=>"mailto:contato@123projetei.com", "ano"=>"2015", "municipio"=>"Rio Grande - RS", "nome"=>"123Projetei", "siteDaStartup"=>"www.123projetei.com/"], "580"=>["site"=>"https://startupbase.com.br/c/startups/nsect-protein-ingredientes-sustentaveis", "ano"=>"2022", "municipio"=>"Campo Bom - RS", "nome"=>"!nsect Protein - Ingredientes Sustentáveis"], "501"=>["site"=>"https://startupbase.com.br/c/startups/bicharia", "ano"=>"2012", "municipio"=>"Porto Alegre - RS", "nome"=>"Bicharia", "siteDaStartup"=>"www.bicharia.com.br"], "502"=>["site"=>"https://startupbase.com.br/c/startups/beta-2", "emailDaStartup"=>"mailto:beta2games@gmail.com", "ano"=>"2013", "municipio"=>"Rio Grande - RS", "nome"=>"Beta 2", "siteDaStartup"=>"www.beta2games.com/"], "503"=>["site"=>"https://startupbase.com.br/c/startups/bepet", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"BePet", "siteDaStartup"=>"www.bepet.com.br"], "504"=>["site"=>"https://startupbase.com.br/c/startups/bendito-verde", "emailDaStartup"=>"mailto:contato@benditoverde.com", "ano"=>"2014", "municipio"=>"Porto Alegre - RS", "nome"=>"Bendito Verde", "siteDaStartup"=>"www.benditoverde.com/"], "505"=>["site"=>"https://startupbase.com.br/c/startups/bemp", "emailDaStartup"=>"mailto:faz@bemp.com.br", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"BEMP", "siteDaStartup"=>"bemp.com.br"], "506"=>["site"=>"https://startupbase.com.br/c/startups/befer-agroindustrial-e-comercial-ltda", "emailDaStartup"=>"mailto:contato@befer.eco.br", "ano"=>"2013", "municipio"=>"Porto Alegre - RS", "nome"=>"Befer Agroindustrial e Comercial Ltda", "siteDaStartup"=>"befer.eco.br"], "507"=>["site"=>"https://startupbase.com.br/c/startups/beetchat", "emailDaStartup"=>"mailto:fabiano@beetchat.com", "ano"=>"2013", "municipio"=>"Caxias do Sul - RS", "nome"=>"Beetchat", "siteDaStartup"=>"www.beetchat.com"], "508"=>["site"=>"https://startupbase.com.br/c/startups/beer-car", "emailDaStartup"=>"mailto:emaildobeercar@gmail.com", "ano"=>"2017", "municipio"=>"Porto Alegre - RS", "nome"=>"beer car", "siteDaStartup"=>"www.beercar.com.br"], "509"=>["site"=>"https://startupbase.com.br/c/startups/bee-free-app-tecnologia-e-servicos-ltda", "emailDaStartup"=>"mailto:adm@beefreeapp.com.br", "ano"=>"2020", "municipio"=>"Porto Alegre - RS", "nome"=>"Bee Free App Tecnologia e Serviços Ltda", "siteDaStartup"=>"www.beefreeapp.com.br"], "510"=>["site"=>"https://startupbase.com.br/c/startups/beaversystems", "emailDaStartup"=>"mailto:atendimento@beaversystems.com.br", "ano"=>"2016", "municipio"=>"Porto Alegre - RS", "nome"=>"BeaverSystems", "siteDaStartup"=>"beaverroom.com.br"], "511"=>["site"=>"https://startupbase.com.br/c/startups/beagle-ship", "emailDaStartup"=>"mailto:contato@beagleship.com.br", "ano"=>"2012", "municipio"=>"Santa Maria - RS", "nome"=>"Beagle Ship", "siteDaStartup"=>"www.beagleship.com.br/"]];

///*/ //$id = 383;
//foreach ($a as $item) {
//    echo $id . ",";
//    echo $item['nome'] . ',,';
//    if (isset($item['email'])) {
//        echo str_replace('mailto:','',$item['email']) . ",,,";
//    } else {
//        echo ",,,";
//    }
//    if (isset($item['siteDaStartup'])) {
//        echo $item['siteDaStartup'] . ',';
//    } else {
//    echo ",";
//    }
//    $muni = explode('-', $item['municipio']);
//    echo trim($muni[0]) . ',' . trim($muni[1]) ."<br>";
//    $id++;
//}

$antigos = array(
    "Agrare",
    "Atendare",
    "Bi Machine",
    "BTi Estratégica",
    "Coleta Verde",
    "Demander",
    "Driva",
    "Eu Reciclo ",
    "Greenmotor ",
    "HERO Industrial Automation",
    "Hex",
    "Kretos",
    "meuResiduo",
    "Moderniza ",
    "Mundi Online",
    "oSucateiro",
    "Performance Vegetal",
    "Pmetric",
    "QualyFull",
    "Quimea Ambiental",
    "Soffiatti",
    "Sqed",
    "StarLearning",
    "TerraMares",
    "Tomasi",
    "uMove.me",
    "X4",
    "Zéfiro",
    "Hapy",
    "BEMP",
    "PMETRIC",
    "ChoppFácil",
    "Synérgya",
    "OPTIM",
    "PremaCar",
    "Desenvolve",
    "Uhuu",
    "Agidesk",
    "STE - Science Technology & Engeneering",
    "DevPampa",
    "Marina Tecnologia",
    "Cognitiva Brasil",
    "Azleads",
    "ContDigital ",
    "Apoia.se",
    "EdufySistemas",
    "PagCripto",
    "Lumiun",
    "Attivilog",
    "InovaPictor",
    "Postmetria - Inteligência de Mercado",
    "Minha Visita",
    "Fácil Consulta",
    "DietBox",
    "Getmo",
    "DonaMaid",
    "Piipee",
    "Deskfy",
    "E-Aware ",
    "Zeeng",
    "Townsq",
    "LinkLei",
    "Diario Escola",
    "Soltech",
    "Campear ",
    "iZiCake",
    "Plick Soluções Contábeis",
    "TopWay",
    "Latos",
    "Isobio",
    "Portal Fronteiriço",
    "AERO Topografia",
    "Trifácil",
    "36Z",
    "Scoreplan",
    "Zeit",
    "REGENERA MOLÉCULAS DO MAR",
    "Evcom",
    "Plataforma Análise74",
    "Sirros IoT",
    "Uniway School",
    "Jetimob",
    "SUVic",
    "YOURS BANK",
    "SolucioneRH ",
    "Green Next",
    "Privacy Tools",
    "Alloy",
    "Doutor Call",
    "Ziel Engenharia",
    "N1Office",
    "FREECASH",
    "Edsun",
    "FLUIDSTATE",
    "Scallar",
    "DAPASOFT",
    "Animopixel",
    "Gáutica",
    "IMaps Business Intelligence",
    "Hoopster",
    "Aprogend",
    "Pix Force",
    "Modelo Vencedor",
    "Cluster21",
    "Vivências Turismo Geográfico",
    "Colocker",
    "Int6",
    "BeyondDomotics",
    "BeOn",
    "Tribeca",
    "Gomining",
    "Fox IoT",
    "INFOTech",
    "RedeSíndicos",
    "GH Branding",
    "Mr. Dev Studio",
    "MyClub",
    "Otimizy Sistemas Inteligentes Ltda",
    "Vortilog",
    "IW Soluções Inteligentes Consultoria Ltda.",
    "Mercado Regional",
    "Agrocloud",
    "Prediza",
    "UBISTART",
    "Cíngulo",
    "hotelflow",
    "Eurekka",
    "Impare",
    "Konecty",
    "ACIZ",
    "Satoshi Investimentos",
    "Tag Livros",
    "Garupa",
    "MAGEN",
    "Arpac",
    "Allexo Tecnologia",
    "The Fixt",
    "Queen Mob",
    "No Faro",
    "Anota AI",
    "QuantoSobra",
    "Melhor Envio",
    "MPQuatro",
    "Nexo",
    "Me Salva!",
    "Aegro",
    "Refresher",
    "Otimizare",
    "CloudStyle",
    "Octanage ",
    "VemVendê",
    "Idiomus",
    "CheFigo!",
    "Zaply",
    "Barp Digital",
    "SuperPlayer",
    "Essent Jus",
    "MotionAnimação",
    "TaoKombucha",
    "Delivery Much",
    "Wedy",
    "WeFix",
    "Prosumir",
    "FeelJoy",
    "P3DENTAL",
    "Checkplant",
    "Webmagister",
    "SkyDrones",
    "BE220",
    "Ubots",
    "SaveFarm",
    "Mconf",
    "Space Hunters",
    "Dobra",
    "Atraia",
    "Pix Midia",
    "Urbe.me",
    "MestreSearch",
    "GuiaInvest",
    "Nine Feet Drones",
    "OnHere",
    "Garota do Site",
    "Tom Ticket",
    "Teraware",
    "Websilos",
    "Trashin",
    "Suitable",
    "Star Learning",
    "Reemby",
    "OnePercent",
    "AlterVision",
    "NewworkApps",
    "Nethomes",
    "Needdigital",
    "Mooh360",
    "Auster Tecnologia",
    "Attivilog",
    "Clube 60",
    "Clube Share",
    "Criação .cc",
    "DeliveryVip",
    "DigiFarmz",
    "Entreguei",
    "Fábrica de Contabilidade",
    "Get Commerce",
    "Hygia Saúde",
    "INBEAUTY BRASIL",
    "MAGEN",
    "Ipay Soluções Financeiras",
    "X4 Tecnologia",
    "Constructin",
    "Saipos Serviços de Software Ltda ",
    "Otimizare",
    "RMA TECH",
    "Sinconstruct",
    "SBPA SIMULATORS",
    "Impare",
    "Raks",
    "Potabil",
    "Valencia Serviços de Energia Ltda",
    "Silo verde",
    "Rise Software",
    "First Planner",
    "Reserve 4Me",
    "HIGH LEVEL",
    "XLabs Security",
    "Plural",
    "FazComex",
    "LupaPet",
    "SOS Raios",
    "Acid",
    "Ayga",
    "Valorize",
    "iAgree",
    "iCybersec",
    "Relieve to Live",
    "Usphera XR",
    "Clinia",
    "Faba",
    "Bio Science",
    "Eagle Care",
    "Biosens",
    "Tem Médicos",
    "Núcleo Vitro",
    "Aegro",
    "Lupora",
    "Weecaps",
    "Crops Team",
    "Aeromovel Brasil S.A",
    "All4Conn Tecnloogia",
    "Creare Sistemas",
    "egSYS",
    "Aquaflot",
    "Arbra",
    "Aulalivre",
    "Beeit",
    "Bioin",
    "Bioplus",
    "Computer Aid",
    "Data Mindus",
    "Esos Technology",
    "Falker",
    "Hard Fun Studios",
    "i9 Acess",
    "Instor",
    "Jomon",
    "Maiara Trombini - Consultoria em Marketing Estratégico",
    "Otus Solutions",
    "Pets du Monde",
    "Ponfac",
    "Sentimotor",
    "Solid Invent",
    "Sourtec",
    "STE",
    "Stresstec",
    "Surya Digital",
    "System Advisor",
    "Tera",
    "Tri Solutions",
    "Vou Construir ",
    "Nuinset",
    "Ignis",
    "Magein",
    "Akitti Acessórios",
    "Astro Branding",
    "B2B Reservas",
    "B a Z",
    "BCS Eventos",
    "Be Flow",
    "Bertic",
    "Bravosul",
    "Digitalliza",
    "DmaisE",
    "Dublauto",
    "Eagles",
    "Easy Pro",
    "Evlu",
    "Fala Cidadão",
    "FK Biotec",
    "Geossintec",
    "Global Consulter",
    "Goya Labs",
    "Growdev",
    "Hanisch",
    "Health ID",
    "Higra ",
    "iCoLab",
    "Inlite",
    "Judice Office",
    "KSI Edge Brasil ",
    "Lifelab",
    "Marke ",
    "Me Veste",
    "Mog Comunicação",
    "Mover Acessibilidade ",
    "NeoVech",
    "Nurseme",
    "Packbrand",
    "Pipeor",
    "Rankine",
    "Refit",
    "Sculpt",
    "Secullum",
    "Serall",
    "Solleda",
    "SolucioneRH",
    "Stargene ",
    "Startaideia",
    "Tae ",
    "TGR Studio",
    "Toth Lifecare",
    "Varejo Positivo",
    "Ventiur ",
    "Vib Master",
    "Wirklich",
    "Ziel Biosciences",
    "Zletric",
    "OvinoPro",
    "VastoAgro",
    "Creatus",
    "Techniken",
    "Symcore",
    "Teia Labs",
    "Lev Compliance",
    "Hopeful",
    "HealthPlay",
    "Time da Eva",
    "Blox Education",
    "Eduvem",
    "Sevenia",
    "Energia das Coisas",
    "Payer",
    "DMG Financeira",
    "Phi",
    "Safe 2 Pay",
    "MS Contabilidade ",
    "Nexxo",
    "ConnectBe",
    "GreenMotor",
    "Sqed",
    "Indusmart",
    "Focu Conexões Inteligentes",
    "Ideia à vista",
    "Lydia",
    "Mais Abelhas",
    "Nanowear",
    "4lugo",
    "Soha",
    "XL7 Data Science",
    "Bee Free",
    "CardioBreath",
    "Exper Health",
    "Nutrition Thinking",
    "WebMed",
    "Optix",
    "Soul.Med",
    "Tecnosenior",
    "Mais Bonita Todo Dia",
    "Pede que Nutre",
    "Olhar 180",
    "Rakho-Med",
    "Sisqualis",
    "Zuna - Estágios sem Intermediários",
    "ZUM.SPACE",
    "Ztar Tecnologia da Informação",
    "ZHERO SERVICOS E PESQUISAS EM TECNOLOGIA LTDA",
    "ZenFisio",
    "YetPet",
    "XML4ME",
    "Xmart Retail",
    "XLabs ON-Security",
    "WTF! School",
    "WS Work",
    "Workamamy",
    "WORK IT",
    "WiseTutors",
    "Wine Valley Hub",
    "WideIntelligence",
    "WHIZ4 Tecnologia",
    "WGET ENERGY",
    "Welike Influencers",
    "WeConecta",
    "Websilos Marketplace e Educação Corporativa",
    "we fix",
    "We Closet",
    "WBIO",
    "Warren Brasil",
    "WarningBox",
    "VTRINE",
    "Voltaico Soluções em Energia Solar Ltda.",
    "Volpe Luxo Inteligente",
    "Voalá Imagens Aéreas",
    "Viver My Way",
    "Vital O Guia da sua Aposentadoria",
    "ViaObjects",
    "Venits",
    "Velivery",
    "Vambora",
    "Valência- Energia Sustentável",
    "Vale do Sulício",
    "Vaga Compartilhada",
    "Utyl",
    "Utopia Game Studio",
    "Urbotip",
    "URBE.ME",
    "URBANPLAN",
    "Urban Farmcy",
    "UNQUO Technology",
    "Unbroken",
    "Umbler",
    "UEX - User Education Experience",
    "Uangoo",
    "Troco Dados",
    "Tripnner",
    "Triider",
    "Trice",
    "Traust.IT",
    "Trajô",
    "TownSq",
    "TopStars",
    "TomTicket",
    "Tomaz",
    "Toca de Aluguel",
    "TLEK",
    "TheFixt",
    "TeuBomNegocio",
    "Teste",
    "Tebaldi Digital",
    "Tarefa.co",
    "Talos soluções de dados",
    "SuperMídia Digital Ltda",
    "Supercooler",
    "Suaposta",
    "Sttalo",
    "SShampoo",
    "Splora",
    "SpinoBike",
    "Souking",
    "Sou4w",
    "Sou Mãe",
    "Solysion",
    "SOLTECH - Fintech",
    "Solleda Energia Solar Limpa MP Comercial Ltda",
    "snam.io",
    "SmartCase",
    "Smart Fatura",
    "Skrow Innovation",
    "Skeel Recrutamento Inteligente",
    "Site Campus",
    "Sistema Sul Tech",
    "Sirros",
    "Sinergia Criativa",
    "Simpay",
    "Shoptutor",
    "Sheepdog Data Storytelling",
    "Serviçando",
    "Serf Drytech",
    "SCREEN CAR",
    "Santo Contrato",
    "Saipos",
    "Safra Online",
    "Safe2Pay",
    "RSbloggers",
    "Route",
    "Rosso Assessoria em Licitações Ltda",
    "Rocket.Chat",
    "Reset Tecnologia",
    "Reserve 4me",
    "Requisitus",
    "Reprosis",
    "Replays",
    "ReNature",
    "Reemby - Reembolso Corporativo",
    "Real Networking",
    "Rank Monitor",
    "Ragazze",
    "Quero Frete",
    "Quanto custa morar sozinho",
    "QQCTech",
    "Qoferta",
    "Pyxie",
    "Prosa Electric Control",
    "Prontuário Verde",
    "Progenes",
    "Presto",
    "Precisão em Campo",
    "Prakaranga",
    "POX",
    "Postmetria",
    "Polvo Louco",
    "Podange Smart Wear",
    "PME Academy",
    "PME Academy Educação Empresarial",
    "PlugBuy",
    "Playce",
    "Play Delivery",
    "Plataforma Músicos",
    "Plantário",
    "Planest",
    "Pixforce",
    "Pix Mídia/ ImidiaTV",
    "Pix Mídia",
    "Pilotum Tecnologia e Gestão de Entregas",
    "PETCARD",
    "Pega a Chave",
    "Pedra Circular",
    "Papyrus",
    "Pange.as",
    "Painel de Preços da Construção",
    "Oztra",
    "OVYVA",
    "Ouppis",
    "OSucateiro.com",
    "Órulo",
    "Orlla Energia",
    "Origems",
    "OptMob",
    "Optimize",
    "Op’n’Go",
    "Opluss",
    "Onhere",
    "OnData",
    "OnBoy",
    "OmniCar",
    "Omine",
    "Oli Multiagência",
    "Oka Coliving",
    "Octanage Podcast",
    "OCKSA",
    "O Financeiro Online",
    "O AMOR É SIMPLES",
    "Nurture",
    "NORTE COMPLIANCE",
    "NoHarm.ai",
    "Nodo",
    "NOC",
    "Nine Feet Team",
    "NEPHI",
    "Negras Plurais",
    "Needdigital Sistema de Monitoramento Ambiental Wireless",
    "Naxia Digital",
    "NAU25 Ex/cola de Empreendedores",
    "NativiAir Tecnologia",
    "Natebits Studio",
    "Natália Lord",
    "Nas Lojas",
    "NANOWEAR",
    "NANOPLUS",
    "NANOgeneous",
    "Mutuus Seguros",
    "Mulheres de Performance",
    "Mownah Tecnologia",
    "Moveideias",
    "Mova - Tecnologia Assistiva",
    "Morcloud",
    "Moosica",
    "Mooh 360° Adnetwork",
    "MontaAí.com",
    "MonitorGov",
    "ModeloVencedor",
    "Mocka",
    "Mobile Editora Digital",
    "Mobibox",
    "Mobart",
    "Minutfin",
    "Minovelt",
    "MINHA ESCOLA",
    "Mind Gestão Sustentável",
    "Migra",
    "MeuEventoAqui",
    "Meu Guia Digital",
    "Mestre Search",
    "Mercosur Tech",
    "Mercadômetro Pesquisa Salarial",
    "Melhor Anfitião",
    "Megahack",
    "Mega Modas e Info",
    "Meerkat",
    "MEEMPRESTA",
    "MEDICAL SALES HUB",
    "Mediar",
    "Mecânico Delivery",
    "MCurie",
    "Mconf Tecnologia",
    "Mattje Consultoria",
    "Material Barato",
    "MatchPal",
    "mapspet",
    "Manumaint",
    "Manu CMMS",
    "makadu.live",
    "Mais Shows",
    "MagoDrive",
    "Lotadata",
    "Loop Bike Sharing",
    "Local Chat",
    "Lixion",
    "Linkadu",
    "Likin.do Brasil",
    "Life On - Soluções em Omni Channel",
    "Licitweb",
    "Leve-me",
    "LBM Data",
    "LancerYou",
    "Lanceiros Tech",
    "LANÇA FILMES",
    "Kynos Technologies",
    "Ksoslegal",
    "kretos Solução em Recursos Humanos Ltda",
    "Kobe",
    "KEMIO",
    "JusAPI",
    "Jou Lavanderia",
    "JOSE LUIZ MARTINS",
    "Jobs Start",
    "Jerônimo Machado | Marketing Digital",
    "James Tip",
    "iWEb - Desenvolvimento de Sistemas de Meios de Pagamento Limitada",
    "Iuggo",
    "ItStalk",
    "itquetas",
    "Isobio - Substâncias de referência bioativas",
    "Iris",
    "Inventsys",
    "Insecta Shoes",
    "INNOVEA HUB",
    "Infinitum",
    "INDUSMART",
    "Indeorum",
    "Imagu Labs",
    "IlexTec",
    "IDT",
    "hygia",
    "Horty",
    "Horizon IT",
    "HoneyDreams",
    "Herself",
    "Hermit Crab",
    "Hemotify",
    "Helplit Tecnologia em educaçao Ltda.",
    "Health ID Lab",
    "Gurvam",
    "Guia de Terapeutas",
    "Growth - Food Business Design",
    "GreenTech",
    "GreenBird Club",
    "Gray Company",
    "Granaai",
    "GRAM",
    "Goulmi",
    "Goocloud - Consultoria em TI",
    "Gongo",
    "Gomining Analise de Dados Ltda",
    "GoDoc",
    "Goclin",
    "Glabs.digital",
    "Gabriel Agne",
    "Frete Facil.com",
    "FREECASH. CONSUMO DO BEM.",
    "Freecash",
    "Flimbo",
    "Flight Help Brasil",
    "Fleeter",
    "Flashboy",
    "Financeiramente",
    "Fight Analytics",
    "FiberSchool",
    "fernanda knebel",
    "FeelJoy Inteligent Foods",
    "FeedByQuiz",
    "FazMercado",
    "Farma Express",
    "Famosa do Site",
    "Fala Cidadao Tecnologia e Servicos de Internet Ltda",
    "Eye4Tech",
    "Expin",
    "Eventos já!",
    "Eureka Paint",
    "Eu Amo Criança Outlet",
    "Eterno Software Juridico",
    "ESTIBORDO.SYS",
    "Estande.me",
    "Esportche",
    "Escola do Futebol",
    "Escola Caxias Criativa",
    "EOS Studio",
    "Emprezaz.com",
    "Elofy",
    "Elede",
    "Economiza Club",
    "Econodata",
    "EASY QUADRAS",
    "Easy Market Comércio de Alimentos Ltda. ME",
    "E-Aware",
    "Dronagro",
    "DRESSiT",
    "DRAWingsBOX",
    "dr.mob",
    "Doshi",
    "Donamaid",
    "Domi House",
    "DoctorCondo",
    "Doc.Space Documentos Digitais",
    "Diosa - Mão de Obra Feminina",
    "DigiFarmz Smart Agriculture",
    "DIETBOX",
    "Dieta Express",
    "DICA - Digital Campanha",
    "DiagnoSys",
    "DGB Animação",
    "DevPampa Sistemas Eficientes",
    "Devorando",
    "Desenfila",
    "Delivery in Box",
    "Deixa Comigo",
    "Deeper",
    "DeepDataMD",
    "DCM",
    "Dataglass",
    "Dataclin Soluções Tecnológicas Ltda",
    "Custo Expresso",
    "cur.to",
    "CUIDAQUI",
    "CTE Brasil",
    "Cstorm",
    "CryptoCloudBrasil",
    "Croqui",
    "CRM PipeRun",
    "Criativando",
    "Cozinhe.me",
    "CowMed",
    "Coolab",
    "Conveynet",
    "ContDigital Contabilidade Online",
    "ContaÁgil Contabilidade Online",
    "Construct IN",
    "Connect",
    "Conduweb",
    "Conceptu",
    "Cogni",
    "Codeland",
    "CO.ARQ Construções Modulares",
    "CLUBE 60",
    "ClickMudanças",
    "Click Gás",
    "Clic Health ID",
    "Clic Corretores",
    "Clear Consulting",
    "ClassAdvisor",
    "ChartPay",
    "Cervejaria IMPLICANTES",
    "Central do Franqueado",
    "CenaZERO",
    "CEANNE Telemedicina",
    "CapWise",
    "Capese",
    "Canvas360",
    "Campear",
    "CakeERP",
    "Café Inteligência Imobiliária",
    "Café com Soluções",
    "ByCrop",
    "Busque Músicos",
    "Bridger Up",
    "Breadsy",
    "Bravas Sistemas Ltda Me",
    "Brasil Paralelo",
    "Brasau",
    "BRANDOR MARCAS",
    "BoccacioMoreno Advogados",
    "Blaxp",
    "biziness",
    "BioHealth",
    "BIMachine",
    "Bico",
    "Be220 Conteúdo Digital",
    "Be On - Segurança Colaborativa",
    "BAZ Negócios de A a Z",
    "Bandolim - Maestro",
    "Bambu Alimentos",
    "BalladApp",
    "Bae Digital Ltda",
    "Baby Gym - Academia para bebês",
    "Baby Check-in",
    "Aztec Online Solutions",
    "AXBAdministradoradeCartõesdeCrédito",
    "Avelã Big Data",
    "Avctoris",
    "Avant Solar",
    "Avacon Technology",
    "Autoridade Fitness",
    "AUREA",
    "Aprocci",
    "Aposentado Em Ação",
    "APECATUS",
    "Any3",
    "Anima Pocket",
    "Analitus",
    "amipet",
    "Alugadireto",
    "Aluga Mais App Ltda",
    "Alu",
    "Alster",
    "Alpago",
    "ai - acheimoveis.online",
    "Agroeducar",
    "Agricon Business",
    "Agrare - Tecnologia e Gestão",
    "AgexTec",
    "Agente G Soluções Empresariais",
    "Agencie.me",
    "AgenciaTTB",
    "Afortunado",
    "Aeronaves Remotamente Pilotadas de Alta Capacidade",
    "Adeus Rotina",
    "addicionei",
    "Acerto Fácil",
    "Acelera MEI",
    "ABREAST PROSPECÇÃO CORPORATIVA",
    "ABM LUX",
    "AAdTools",
    "A00s",
    "4POR100",
    "4all Tecnologia",
    "400g",
    "3S - Solar Sustainable Solutions",
    "3layer Tecnologia",
    "3DProtos",
    "2bface",
    "1Bem",
    "123Projetei",
    "!nsect Protein - Ingredientes Sustentáveis",
    "Bicharia",
    "Beta 2",
    "BePet",
    "Bendito Verde",
    "Befer Agroindustrial e Comercial Ltda",
    "Beetchat",
    "beer car",
    "Bee Free App Tecnologia e Serviços Ltda",
    "BeaverSystems",
    "Beagle Ship"
    );
$id = 796;
foreach ($a as $item) {
    if (!in_array($item['nome'], $antigos)) {
        echo $id . ",";
        echo $item['nome'] . ',,';
        if (isset($item['emailDaStartup'])) {
            echo str_replace('mailto:', '', $item['emailDaStartup']) . ",,,";
        } else {
            echo ",,,";
        }
        if (isset($item['siteDaStartup'])) {
            echo $item['siteDaStartup'] . ',';
        } else {
            echo ",";
        }
        $muni = explode('-', $item['municipio']);
        echo trim($muni[0]) . ',' . trim($muni[1]) . "<br>";
        $id++;
    }

}